### ISSUE TITLE
Crash on Server - While using blocks server crashed - Minecraft 1.12.2 Forge

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TridentMC/ArchitectureCraft#10]
Full Log
https://gist.github.com/P3rf3ctXZer0/7f93a8e552a301638d09f9116b309ed8

Cherry Picked Log
https://gist.github.com/P3rf3ctXZer0/c8bea4556f5303186783b41b8d440043

This crash is unique it may have to do with Thutcore @Thutmose I also see errors directly related to Architecturecraft though @darkevilmac

**Comment by P3rf3ctXZer0** [comment]
I believe these are connected.
https://github.com/elytra/ArchitectureCraft/issues/9

https://github.com/Thutmose/Thut/issues/67

**Comment by Thutmose** [comment]
looks to me like you are running the mod on the wrong version of minecraft for where it was compiled

**Comment by P3rf3ctXZer0** [comment]
@darkevilmac I can no longer connect to the server ... 
https://gist.github.com/P3rf3ctXZer0/15cbb619d72a7f9033d4baae5fe3b718

I was forced to remove the mod for the time being :'(

**Comment by exaskye** [comment]
Looks like ArchitectureCraft is trying to load client-side model information on the server-side to calculate the bounding box.
