### ISSUE TITLE
question about a possible update of the mod to version 1.14.4

### ISSUE THREAD

**Issue by Luismi28** [TridentMC/ArchitectureCraft#103]
@TridentMC I wanted to know if this mod will migrate to version 1.14.4?
Since the creator of the original mod retired, he wanted to know if you who updated it to version 1.12.2 could do the same for version 1.14.4

**Comment by CalmBit** [comment]
1.14.4 is not being targeted. Development is currently being focused on making the mod work with 1.15+. Backporting the mod will almost certainly not happen. Sorry.
