### ISSUE TITLE
Continued Discussion for #64 - Closed as duplicate

### ISSUE THREAD

**Issue by ben-mkiv** [TridentMC/ArchitectureCraft#104]
yea keep censoring your git issues, blaming other mods because you didn't get the problem

seriously what kind of fucked up behavior is it to delete posts?!

This can't be solved by a config!
sealed
![](https://i.imgur.com/yzQMyt8.png)

not sealed
![](https://i.imgur.com/3TXRg1N.png)

just state that you aren't interested in the extra work, instead of blaming other mods

**Comment by darkevilmac** [comment]
It also can't be solved by the API you've listed. As noted this is not an issue that will be fixed.

Cheers,
Benjamin
