### ISSUE TITLE
AC is not adhering to 'normal' MC rotation conventions

### ISSUE THREAD

**Issue by TheProtoss-YT** [TridentMC/ArchitectureCraft#105]
This mod has never behaved very well with Schematic/Editing Mods such as World Edit or Recurrent Complex, this makes it difficult to work with in any mod pack development as it mucks up in world gen unless you lock your schematic in it's original orientation. My question is can it be corrected? Has this been mentioned before? 

Currently Running:
- Version 1.12-3.98
- Minecraft version 1.12.2
- Forge 14.23.5.2847

![image](https://user-images.githubusercontent.com/35242371/95420877-19ec7700-08f1-11eb-971a-ef6e209ec4f0.png)

![image](https://user-images.githubusercontent.com/35242371/95420889-1f49c180-08f1-11eb-8f91-34e11b22478b.png)

**Comment by darkevilmac** [comment]
ArchitectureCraft stores its rotations in the actual tile entity and not the blockstate, there's not much that can be done here unfortunately.

**Comment by TheProtoss-YT** [comment]
All good, thank you for the fast response to my inquiry. I understand that would likely require a full rewrite of the core mod.
