### ISSUE TITLE
WorldPainter Problem

### ISSUE THREAD

**Issue by NWPathling** [TridentMC/ArchitectureCraft#110]
I am currently working on a project with your mod as part of a modpack on a server of mine.

It is an on going project which means I have to take it into WorldEdit to make fixes, add new land masses, etc. and then reupload the land to the server. This works fine, however the problem is that the blocks I use are now not there as the original blocks that I added before I took it into World Edit.

Even if I extended the ID's in WorldPainter it still won't work and retain the blocks I have used from ArchitectureCraft - TridentMC Version.

Could someone help me with how to fix this problem, ASAP. It would be really appreciated.

Also the mods are on both Server side and Client side. If that is a question.

**Comment by darkevilmac** [comment]
ArchitectureCraft uses tile entities to store data, unless WorldPainter supports setting tile entities then there isn't a solution.
