### ISSUE TITLE
Crash on startup 1.16.3

### ISSUE THREAD

**Issue by MinuteLicence** [TridentMC/ArchitectureCraft#113]
Thanks for reporting an issue to a Trident project!

When reporting an issue to a Trident project, please make sure to include:

- 

Version of mod Architecturecraft-1.16-3.146-all.jar
Minecraft version 1.16.5 & 1.16.3
Forge version - any 

Gist below.
https://gist.github.com/MinuteLicence/7322c96c0ba2082d61373641f2a208dd

**Comment by darkevilmac** [comment]
None of my mods are even remotely stable on 1.16 yet.
