### ISSUE TITLE
Texture size issue and direction.

### ISSUE THREAD

**Issue by Rissning** [TridentMC/ArchitectureCraft#114]
Hey.
Minecraft Eternal currently version 1.3.7.1

I love you`re ArchitectureCraft mod and it makes for a little more ease than littletiles everything. The issue I get with it on bigger works is when i have to make a wall next to every corner and I wondered if it was possible to have the arrow keys interact with the blocks to turn it. 

Another problem is its interaction with "Chisel". Many of the blocks have wrong direction and size scale.
Below im using "arrayed bricks" from normal stone brick. The side is wrong way and the texture is scaled down for some reason making it look different that the original block.

![2021-04-03_15 27 22](https://user-images.githubusercontent.com/81863946/113480099-edc24500-9492-11eb-8336-5bd7b211391c.png)

I totaly understand if nothing is done to this matter since it be tedious to do every chiselblock, but I felt to atleast report of this so its noted. Thanks for the lovely mod you guys created:)

**Comment by darkevilmac** [comment]
If I had to guess this is relate to chisel's connected textures feature, there's not a whole lot I can do here outside of special casing which I really don't want to do.
