### ISSUE TITLE
g l i t c h e d   w i n d o w s

### ISSUE THREAD

**Issue by Czebosak** [TridentMC/ArchitectureCraft#116]
ummmm.... Is this normal?
![image](https://user-images.githubusercontent.com/79370971/138584330-72877d6d-61d8-4adc-bc10-f1bce6e0157e.png)

Mod version:
3.98
Minicraft:
1.12.2
Forge:
14.23.5.28
log:
[latest.log](https://github.com/TridentMC/ArchitectureCraft/files/7404235/latest.log)
54

**Comment by darkevilmac** [comment]
This is caused by optifine.
