### ISSUE TITLE
Bug with stairs and slab

### ISSUE THREAD

**Issue by Dvneyr** [TridentMC/ArchitectureCraft#117]
Hello ! I noticed some bugs with the textures of the stairs and the slabs.
Minecraft 1.12.2
Optifine G5
forge 1.12.2-14.23.5.2859
https://gist.github.com/Dvneyr/090f7f593c5d11907c765601a2455b67

Some pictures of the bug
![2021-12-12_16 24 26](https://user-images.githubusercontent.com/45698709/145719823-60e13b6a-9bda-4d9f-a969-dc316c46eec6.png)
![2021-12-12_16 36 45](https://user-images.githubusercontent.com/45698709/145719829-82b74356-370c-4f51-a245-5366f7533a45.png)

The first bug happens in multiplayer
The second one happens in both singleplayer and multiplayer
Here is the list of mods I'm using
![image](https://user-images.githubusercontent.com/45698709/145719881-02e2abff-a9e4-4451-92c0-d31fdd9f940b.png)
I tried updating forge, the mod, optifine ... but nothing seems to work. I also tried multiples times to reload the textures, desactivated connected textures, AA, Anisotropic filters ...

**Comment by mteruggi** [comment]
if you have a shader its happend cuz the shader

**Comment by Dvneyr** [comment]
I don't have a shader

**Comment by mteruggi** [comment]
did you try to remove all the mods and test only with architecture craft to check if the issue came from another mod?

**Comment by darkevilmac** [comment]
This is caused by optifine.
