### ISSUE TITLE
Crash report - one of yours?

### ISSUE THREAD

**Issue by Nexusdog** [TridentMC/ArchitectureCraft#13]
Crashed while in the arch table, trying to use Chiseled effect marble

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.2-104.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  FarseekCoreMod (Farseek-1.12-2.2.1.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
  DummyPlugin (ForgeEndertech-1.12-3.0.1.0-build.0012.jar)
  BIFLoader (BowInfinityFix-1.11.x-1.12.x-rv5.jar)
  MalisisSwitchesPlugin (malisisswitches-1.12-5.0.0.jar)
  llibrary (llibrary-1.7.7-1.12.jar)
  BCModPlugin (backpacks 1.12 - 3.3.2.jar)
  MalisisCorePlugin (malisiscore-1.12-6.0.4.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.0.8.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 11/3/17 12:05 AM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at net.minecraft.inventory.Container.func_184996_a(Container.java:246)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:565)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:392)
	at com.elytradev.architecture.base.BaseGui$Screen.func_73864_a(BaseGui.java:407)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.inventory.Container.func_184996_a(Container.java:246)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:565)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:392)
	at com.elytradev.architecture.base.BaseGui$Screen.func_73864_a(BaseGui.java:407)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: com.elytradev.architecture.client.gui.GuiSawbench

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['nexusdog'/155, l='MpServer', x=619.25, y=64.00, z=-1706.27]]
	Chunk stats: MultiplayerChunkCache: 1681, 1681
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-196,64,-371), Chunk: (at 12,4,13 in -13,-24; contains blocks -208,0,-384 to -193,255,-369), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 3540144 game time, 6052657 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 66 total; [EntitySquid['Squid'/325518, l='MpServer', x=570.10, y=55.66, z=-1746.62], EntityLatchedRenderer['unknown'/1035, l='MpServer', x=619.25, y=64.00, z=-1706.27], EntityBat['Bat'/265743, l='MpServer', x=610.75, y=50.10, z=-1701.40], EntityBat['Bat'/299414, l='MpServer', x=623.75, y=53.10, z=-1722.25], EntityVillager['Villager'/151, l='MpServer', x=654.61, y=63.94, z=-1682.46], EntityBat['Bat'/322076, l='MpServer', x=645.57, y=54.63, z=-1715.54], EntityBat['Bat'/322077, l='MpServer', x=643.50, y=53.10, z=-1715.46], EntityBat['Bat'/322078, l='MpServer', x=641.25, y=54.10, z=-1711.25], EntityCow['Cow'/139689, l='MpServer', x=623.94, y=63.00, z=-1697.98], EntitySquid['Squid'/335924, l='MpServer', x=593.74, y=52.84, z=-1768.38], EntityItem['item.item.beetroot_seeds'/310198, l='MpServer', x=656.57, y=63.94, z=-1678.85], EntitySquid['Squid'/335926, l='MpServer', x=590.66, y=54.38, z=-1768.01], EntityWorm['Worm'/185275, l='MpServer', x=597.50, y=62.50, z=-1688.50], EntityPlayerSP['nexusdog'/155, l='MpServer', x=619.25, y=64.00, z=-1706.27], EntityLatchedRenderer['unknown'/187, l='MpServer', x=8.50, y=65.00, z=8.50], EntitySquid['Squid'/335928, l='MpServer', x=591.71, y=53.10, z=-1767.88], EntityVillager['Olivia'/64, l='MpServer', x=632.07, y=64.00, z=-1664.30], EntityBat['Bat'/255811, l='MpServer', x=609.00, y=35.17, z=-1703.16], EntityVillager['Villager'/65, l='MpServer', x=621.70, y=66.00, z=-1659.30], EntityVillager['Villager'/66, l='MpServer', x=637.22, y=65.00, z=-1663.85], EntityVillager['Andrea'/67, l='MpServer', x=631.30, y=64.00, z=-1664.48], EntityVillager['Tia'/68, l='MpServer', x=621.70, y=64.00, z=-1665.70], EntityPig['Pig'/70, l='MpServer', x=637.03, y=64.00, z=-1676.45], EntityPig['Pig'/71, l='MpServer', x=637.92, y=64.00, z=-1677.50], EntityCow['Cow'/73, l='MpServer', x=636.04, y=64.00, z=-1674.27], EntityCow['Cow'/166347, l='MpServer', x=621.92, y=63.00, z=-1697.84], EntityVillager['Eleanor'/74, l='MpServer', x=636.96, y=64.00, z=-1674.70], EntitySquid['Squid'/345167, l='MpServer', x=578.05, y=55.35, z=-1752.98], EntityVillager['Tia'/75, l='MpServer', x=637.70, y=64.00, z=-1674.70], EntityVillager['Alexander'/76, l='MpServer', x=629.70, y=63.00, z=-1664.26], EntityVillager['Robert'/77, l='MpServer', x=632.53, y=64.00, z=-1673.08], EntityCow['Cow'/33487, l='MpServer', x=621.77, y=63.00, z=-1695.50], EntityVillager['Villager'/79, l='MpServer', x=620.50, y=64.00, z=-1664.64], EntityVillager['Tyler'/81, l='MpServer', x=651.92, y=64.00, z=-1664.50], EntityIronGolem['Iron Golem'/82, l='MpServer', x=627.13, y=64.00, z=-1673.04], EntityVillager['Villager'/83, l='MpServer', x=592.53, y=63.00, z=-1687.43], EntityVillager['Villager'/84, l='MpServer', x=601.45, y=63.00, z=-1674.63], EntitySquid['Squid'/345169, l='MpServer', x=578.90, y=55.98, z=-1761.32], EntityVillager['Penny'/85, l='MpServer', x=607.46, y=63.00, z=-1689.49], EntityWorm['Worm'/185559, l='MpServer', x=595.50, y=62.50, z=-1688.50], EntitySquid['Squid'/345168, l='MpServer', x=578.19, y=54.26, z=-1755.08], EntityVillager['Duane'/86, l='MpServer', x=620.39, y=64.00, z=-1663.92], EntityVillager['Villager'/87, l='MpServer', x=603.38, y=63.00, z=-1681.65], EntitySquid['Squid'/345170, l='MpServer', x=583.44, y=56.45, z=-1763.69], EntityBat['Bat'/171738, l='MpServer', x=604.09, y=50.10, z=-1704.62], EntityWorm['Worm'/89, l='MpServer', x=617.50, y=67.50, z=-1718.50], EntityBat['Bat'/345692, l='MpServer', x=618.77, y=19.90, z=-1731.20], EntityWorm['Worm'/90, l='MpServer', x=617.50, y=67.50, z=-1716.50], EntityBat['Bat'/345695, l='MpServer', x=559.56, y=30.63, z=-1665.75], EntityWorm['Worm'/91, l='MpServer', x=615.50, y=67.50, z=-1716.50], EntityCow['Cow'/31325, l='MpServer', x=621.07, y=63.00, z=-1698.61], EntityWorm['Worm'/185443, l='MpServer', x=595.50, y=62.50, z=-1686.50], EntityBat['Bat'/268901, l='MpServer', x=623.50, y=53.10, z=-1722.25], EntityWorm['Worm'/185184, l='MpServer', x=597.50, y=62.50, z=-1686.50], EntitySquid['Squid'/345063, l='MpServer', x=572.46, y=60.49, z=-1767.65], EntitySquid['Squid'/345062, l='MpServer', x=574.85, y=60.37, z=-1770.18], EntityWorm['Worm'/185060, l='MpServer', x=599.50, y=62.50, z=-1686.50], EntityBat['Bat'/341353, l='MpServer', x=609.01, y=20.16, z=-1653.01], EntityBat['Bat'/341352, l='MpServer', x=609.25, y=14.99, z=-1646.92], EntitySquid['Squid'/345064, l='MpServer', x=566.55, y=59.70, z=-1770.06], EntityCow['Cow'/37486, l='MpServer', x=625.28, y=63.00, z=-1698.93], EntityBat['Bat'/341354, l='MpServer', x=599.06, y=23.02, z=-1645.38], EntityBat['Bat'/344691, l='MpServer', x=619.25, y=22.03, z=-1652.93], EntityWorm['Worm'/184953, l='MpServer', x=599.50, y=62.50, z=-1688.50], EntityCow['Cow'/139135, l='MpServer', x=628.39, y=63.00, z=-1698.58], EntityCow['Cow'/166013, l='MpServer', x=621.90, y=63.00, z=-1698.56]]
	Retry entities: 1 total; [EntityLatchedRenderer['unknown'/187, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 639372424 bytes (609 MB) / 4912807936 bytes (4685 MB) up to 12831227904 bytes (12236 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.40 Powered by Forge 14.21.1.2443 124 mods loaded, 124 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2443.jar) 
	UCHIJAAAA	forge{14.21.1.2443} [Minecraft Forge] (forge-1.12-14.21.1.2443.jar) 
	UCHIJAAAA	ivtoolkit{1.3.3-1.12} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	com.elytradev.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
	UCHIJAAAA	backpacks16840{3.3.2} [Backpacks!] (backpacks 1.12 - 3.3.2.jar) 
	UCHIJAAAA	bowinfinityfix{rv5} [Bow Infinity Fix] (minecraft.jar) 
	UCHIJAAAA	simplebedrolls{1.2.1} [Simple Bedrolls] ([1.12]SimpleBedrolls-1.2.1.jar) 
	UCHIJAAAA	uncraftingtable{1.8-beta6} [Uncrafting Table] ([1.12]UncraftingTable-1.8-beta6.jar) 
	UCHIJAAAA	jei{4.7.11.100} [Just Enough Items] (jei_1.12.2-4.7.11.100.jar) 
	UCHIJAAAA	abyssalcraft{1.9.4-pre-4} [AbyssalCraft] (AbyssalCraft-1.12-1.9.4-pre-4.jar) 
	UCHIJAAAA	ctm{MC1.12-0.2.3.9} [CTM] (CTM-MC1.12-0.2.3.9.jar) 
	UCHIJAAAA	chisel{MC1.12-0.0.14.18} [Chisel] (Chisel-MC1.12-0.0.14.18.jar) 
	UCHIJAAAA	mantle{1.12-1.3.1.21} [Mantle] (Mantle-1.12-1.3.1.21.jar) 
	UCHIJAAAA	tconstruct{1.12-2.7.4.34} [Tinkers' Construct] (TConstruct-1.12-2.7.4.34.jar) 
	UCHIJAAAA	acintegration{1.5.0} [AbyssalCraft Integration] (AbyssalCraft Integration-1.12-1.5.0.jar) 
	UCHIJAAAA	actuallyadditions{1.12.1-r122} [Actually Additions] (ActuallyAdditions-1.12.1-r122.jar) 
	UCHIJAAAA	baubles{1.5.1} [Baubles] (Baubles-1.12-1.5.1.jar) 
	UCHIJAAAA	actuallybaubles{1.1} [Actually Baubles] (ActuallyBaubles-1.12-1.1.jar) 
	UCHIJAAAA	alt{2.0.2} [Additional Loot Tables] (AdditionalLootTables-1.12.1-2.0.2.29.jar) 
	UCHIJAAAA	allthedrops{1.0.1} [All the Drops] (allthedrops-1.11.2-1.0.1-build-T22.jar) 
	UCHIJAAAA	ambientsounds{2.0.0} [AmbientSounds] (AmbientSounds v2.0.8 mc1.12.jar) 
	UCHIJAAAA	architecturecraft{@VERSION@} [ArchitectureCraft] (architecturecraft-1.12-1.20.jar) 
	UCHIJAAAA	quark{r1.2-104} [Quark] (Quark-r1.2-104.jar) 
	UCHIJAAAA	autoreglib{1.3-14} [AutoRegLib] (AutoRegLib-1.3-14.jar) 
	UCHIJAAAA	betterbedrockgen{6.0.2} [BetterBedrockGen] (BetterBedrockGenerator-1.12-6.1.1.jar) 
	UCHIJAAAA	betterunderground{1.0.4} [Better Underground] (betterunderground-1.0.4.jar) 
	UCHIJAAAA	bibliocraft{2.4.3} [BiblioCraft] (BiblioCraft[v2.4.3][MC1.12.0].jar) 
	UCHIJAAAA	natura{1.12-4.3.0.17} [Natura] (Natura-1.12-4.3.0.17.jar) 
	UCHIJAAAA	forestry{5.5.6.198} [Forestry] (forestry_1.12.2-5.5.6.198.jar) 
	UCHIJAAAA	binniecore{unspecified} [Binnie Core] (binnie-mods-1.12.2-2.3.1.jar) 
	UCHIJAAAA	binniedesign{1.0} [Binnie's Design] (binnie-mods-1.12.2-2.3.1.jar) 
	UCHIJAAAA	genetics{2.3.1} [Binnie's Genetics] (binnie-mods-1.12.2-2.3.1.jar) 
	UCHIJAAAA	botany{2.3.1} [Binnie's Botany] (binnie-mods-1.12.2-2.3.1.jar) 
	UCHIJAAAA	extrabees{2.3.1} [Binnie's Extra Bees] (binnie-mods-1.12.2-2.3.1.jar) 
	UCHIJAAAA	extratrees{2.3.1} [Binnie's Extra Trees] (binnie-mods-1.12.2-2.3.1.jar) 
	UCHIJAAAA	biomesoplenty{7.0.0.2291} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2291-universal.jar) 
	UCHIJAAAA	birdsnests{2.0.0} [Bird's Nests] (BirdsNests1.12-2.0.0.jar) 
	UCHIJAAAA	bookshelf{2.1.441} [Bookshelf] (Bookshelf-1.12.1-2.1.441.jar) 
	UCHIJAAAA	carryon{1.6.1} [Carry On] (CarryOn MC1.12 v1.6.1.jar) 
	UCHIJAAAA	clarity{1.0} [Clarity] (clarity-1.0.jar) 
	UCHIJAAAA	cleanview{1.12.2-v1} [CleanView] (CleanView-1.12.2-v1.jar) 
	UCHIJAAAA	clockhud{1.4.0} [Clock HUD] (ClockHUD-1.12-1.4.0.jar) 
	UCHIJAAAA	cyclopscore{0.10.21} [Cyclops Core] (CyclopsCore-1.12-0.10.21.jar) 
	UCHIJAAAA	commoncapabilities{1.4.0} [CommonCapabilities] (CommonCapabilities-1.12-1.4.0.jar) 
	UCHIJAAAA	concreteplus{1.1.2} [Concrete Extends] (ConcreteExtends-1.1.2_1.12.jar) 
	UCHIJAAAA	customizeddungeonloot{1.0.1} [§eCustomized Dungeon Loot] (Customized Dungeon Loot (v.1.0.1).jar) 
	UCHIJAAAA	cyclicmagic{1.8.6} [Cyclic] (Cyclic-1.12-1.8.6.jar) 
	UCHIJAAAA	waila{1.8.21} [Waila] (Hwyla-1.8.21-B36_1.12.jar) 
	UCHIJAAAA	darkutils{1.7.171} [Dark Utilities] (DarkUtils-1.12.1-1.7.171.jar) 
	UCHIJAAAA	movingworld{1.12-6.342} [Moving World] (movingworld-1.12-6.342-full.jar) 
	UCHIJAAAA	davincisvessels{@DVESSELSVER@} [Davinci's Vessels] (davincisvessels-1.12-6.337-full.jar) 
	UCHIJAAAA	disenchanter{1.5} [Disenchanter] (disenchanter-[1.12]1.5.jar) 
	UCHIJAAAA	gottschcore{1.1.2} [GottschCore] (GottschCore-mc1.12-v1.1.2.jar) 
	UCHIJAAAA	dungeons2{1.3.1} [Dungeons2!] (Dungeons2-mc1.12-v1.3.1.jar) 
	UCHIJAAAA	dsurround{3.4.7.2} [§3Dynamic Surroundings] (DynamicSurroundings-1.12.2-3.4.7.2.jar) 
	UCHIJAAAA	presets{3.4.7.2} [§3Presets!] (DynamicSurroundings-1.12.2-3.4.7.2.jar) 
	UCHIJAAAA	earthworks{1.3.4.3} [Earthworks] (Earthworks-1.12-1.3.4.3.jar) 
	UCHIJAAAA	elevatorid{1.3.4} [Elevator Mod] (ElevatorMod-1.12-1.3.4.jar) 
	UCHIJAAAA	csb_ench_table{1.1.2} [Lapis Stays in the Enchanting Table] (EnchantingTable-1.12-1.1.2.jar) 
	UCHIJAAAA	enchdesc{1.0.4} [Enchantment Descriptions] (EnchantmentDescriptions-1.12-1.0.4.jar) 
	UCHIJAAAA	everlastingabilities{1.3.5} [EverlastingAbilities] (EverlastingAbilities-1.12-1.3.5.jar) 
	UCHIJAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.12-1.6.4.jar) 
	UCHIJAAAA	farseek{2.2.1} [Farseek] (Farseek-1.12-2.2.1.jar) 
	UCHIJAAAA	fastleafdecay{v13} [Fast Leaf Decay] (FastLeafDecay-v13.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.12-6.6} [Flat Colored Blocks] (flatcoloredblocks-mc1.12-6.6.jar) 
	UCHIJAAAA	forgeendertech{1.12-3.0.1.0} [Forge Endertech] (ForgeEndertech-1.12-3.0.1.0-build.0012.jar) 
	UCHIJAAAA	friendlyfire{1.5.5} [Friendly Fire] (FriendlyFire-1.12-1.5.5.jar) 
	UCHIJAAAA	silentlib{2.2.11} [Silent Lib] (SilentLib-1.12-2.2.11-92.jar) 
	UCHIJAAAA	funores{1.5.7} [Fun Ores] (FunOres-1.12-1.5.7-118.jar) 
	UCHIJAAAA	gamestages{1.0.62} [Game Stages] (GameStages-1.12.1-1.0.62.jar) 
	UCHIJAAAA	gravelminer{6.1.2} [GravelMiner] (GravelMiner_1.12.1-6.1.2.jar) 
	UCHIJAAAA	gravestone{1.0.12} [Gravestone] (GraveStone-1.12-Graves-1.0.12.jar) 
	UCHIJAAAA	guideapi{1.12-2.1.4-57} [Guide-API] (Guide-API-1.12-2.1.4-57.jar) 
	UCHIJAAAA	ichunutil{7.0.2} [iChunUtil] (iChunUtil-1.12.2-7.0.2.jar) 
	UCHIJAAAA	iv{3.0.2} [Improved Villagers] (Improved Villagers-3.0.2.jar) 
	UCHIJAAAA	improvedbackpacks{1.12-1.1.2.0} [Improved Backpacks] (ImprovedBackpacks-1.12-1.1.2.0.jar) 
	UCHIJAAAA	inventorytweaks{1.63+beta.107.015dbec} [Inventory Tweaks] (InventoryTweaks-1.63+beta.107.jar) 
	UCHIJAAAA	itemscroller{0.11.0} [Item Scroller] (itemscroller-1.12.0-0.11.0.jar) 
	UCHIJAAAA	jeibees{0.9.0.5} [JEI Bees] (jeibees-0.9.0.5-mc1.12.2.jar) 
	UCHIJAAAA	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UCHIJAAAA	levelup2{${version}} [Level Up! Reloaded] (Level Up! 2-1.1.8-1.12.jar) 
	UCHIJAAAA	llibrary{1.7.7} [LLibrary] (llibrary-1.7.7-1.12.jar) 
	UCHIJAAAA	malisiscore{1.12-6.0.4} [MalisisCore] (malisiscore-1.12-6.0.4.jar) 
	UCHIJAAAA	malisisblocks{1.12-6.0.2} [Malisis Blocks] (malisisblocks-1.12-6.0.2.jar) 
	UCHIJAAAA	malisisdoors{1.12.2-7.1.0} [MalisisDoors] (malisisdoors-1.12.2-7.1.0.jar) 
	UCHIJAAAA	malisisswitches{1.12-5.0.0} [Malisis Switches] (malisisswitches-1.12-5.0.0.jar) 
	UCHIJAAAA	mobfarm{2.2.1} [Mob Farm] (Mob Farm-1.12-2.2.1.jar) 
	UCHIJAAAA	mobamputation{7.0.0} [MobAmputation] (MobAmputation-1.12.2-7.0.0.jar) 
	UCHIJAAAA	mobdismemberment{7.0.0} [MobDismemberment] (MobDismemberment-1.12.2-7.0.0.jar) 
	UCHIJAAAA	mob_grinding_utils{0.3.2} [mob_grinding_utils] (MobGrindingUtils-0.3.2.jar) 
	UCHIJAAAA	modernlamps{1.0.3} [Modern Lights] (ModernLights-1.0.3_1.12.jar) 
	UCHIJAAAA	moreloottables{0.1.0} [More Loot Tables] (moreloottables-1.12.0-0.1.0.jar) 
	UCHIJAAAA	moreoverlays{1.13} [MoreOverlays] (moreoverlays-1.13-mc1.12.jar) 
	UCHIJAAAA	recipehandler{0.9} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.9(1.12).jar) 
	UCHIJAAAA	notenoughwands{1.5.9} [Not Enough Wands] (notenoughwands-1.12-1.5.9.jar) 
	UCHIJAAAA	oreberries{0.3.2} [Oreberries] (oreberries-1.12.x-0.3.2.jar) 
	UCHIJAAAA	jp.crafterkina.pipes{1.1.0.15} [Pipes] (Pipes-1.12-1.1.0.15.jar) 
	UCHIJAAAA	randomthings{4.0.8} [Random Things] (RandomThings-MC1.12.2-4.0.8.jar) 
	UCHIJAAAA	randomtweaks{1.12.2-1.12.0.0} [RandomTweaks] (randomtweaks-1.12.2-1.12.0.0.jar) 
	UCHIJAAAA	reccomplex{1.4.5} [Recurrent Complex] (RecurrentComplex-1.4.5.1.jar) 
	UCHIJAAAA	redstonepaste{1.7.5} [Redstone Paste] (redstonepaste-mc1.12-1.7.5.jar) 
	UCHIJAAAA	royal{0.25} [Realm Of Yendor's Artifacts of the Lost] (royal-0.25d.jar) 
	UCHIJAAAA	ruins{16.9} [Ruins Mod] (Ruins-1.12.jar) 
	UCHIJAAAA	woodenshears{@MAJOR@.@MINOR@.@REVIS@.@BUILD@} [Wooden Shears] (SBM-WoodenShears-1.12-0.0.1b7.jar) 
	UCHIJAAAA	icc{0.2.2} [Simple Item Collector Chest] (Simple Item Collector Chest-0.2.2.jar) 
	UCHIJAAAA	soundfilters{0.10_for_1.12} [Sound Filters] (SoundFilters-0.10_for_1.12.jar) 
	UCHIJAAAA	spawnercraft{4.0.0} [SpawnerCraft] (SpawnerCraft 1.12-4.0.0.jar) 
	UCHIJAAAA	streams{0.4.1} [Streams] (Streams-1.12-0.4.1.jar) 
	UCHIJAAAA	tinkertoolleveling{1.12-1.0.2b.DEV.1a79301} [Tinkers Tool Leveling] (TinkerToolLeveling-1.12-1.0.2b.jar) 
	UCHIJAAAA	muchmorechickens{1.7} [muchmorechickens] (TMC-1.12-1.7.jar) 
	UCHIJAAAA	toolbelt{1.7.1} [Tool Belt] (ToolBelt-1.12.0-1.7.1.jar) 
	UCHIJAAAA	treechopper{1.2.2} [Tree Chopper] (TreeChopper-1.12-1.2.2.jar) 
	UCHIJAAAA	uncrafted{3.0.1} [Uncrafted] (Uncrafted 1.12  (v.3.0.1).jar) 
	UCHIJAAAA	usefulcows{1.2} [usefulcows] (usefullcows-1.0.2.jar) 
	UCHIJAAAA	veinminer{0.38.1} [Vein Miner] (VeinMiner-1.12-0.38.1.639+134fb1e.jar) 
	UCHIJAAAA	veinminermodsupport{0.38.1} [Mod Support] (VeinMiner-1.12-0.38.1.639+134fb1e.jar) 
	UCHIJAAAA	villagermarket{1.0} [Villager Market] (villagermarket-0.2-HF.jar) 
	UCHIJAAAA	vtt{0.6.4} [Villager Trade Tables] (VillagerTrades-1.12-0.6.4.jar) 
	UCHIJAAAA	wailaharvestability{1.1.12} [Waila Harvestability] (WailaHarvestability-mc1.12-1.1.12.jar) 
	UCHIJAAAA	wawla{2.5.243} [What Are We Looking At] (Wawla-1.12.1-2.5.243.jar) 
	UCHIJAAAA	waystones{4.0.17} [Waystones] (Waystones_1.12.1-4.0.17.jar) 
	UCHIJAAAA	ironic_wdt{1.2} [Weak Drop Tweaks] (WeaKDropTweaks-1.3.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.2-104.jar)
  vazkii.quark.base.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  team.chisel.ctm.client.asm.CTMTransformer
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
FarseekCoreMod (Farseek-1.12-2.2.1.jar)
  farseek.core.FarseekClassTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
  org.blockartistry.DynSurround.asm.Transformer
DummyPlugin (ForgeEndertech-1.12-3.0.1.0-build.0012.jar)
  
BIFLoader (BowInfinityFix-1.11.x-1.12.x-rv5.jar)
  com.github.parker8283.bif.Transformer
MalisisSwitchesPlugin (malisisswitches-1.12-5.0.0.jar)
  net.malisis.switches.asm.MalisisSwitchesTransformer
llibrary (llibrary-1.7.7-1.12.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
BCModPlugin (backpacks 1.12 - 3.3.2.jar)
  brad16840.common.asm.ClassTransformer
MalisisCorePlugin (malisiscore-1.12-6.0.4.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
LoadingPlugin (RandomThings-MC1.12.2-4.0.8.jar)
  lumien.randomthings.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63+beta.107.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Launched Version: 1.12-forge1.12-14.21.1.2443
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: TEAVSRP2.zip (incompatible)
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz

**Comment by darkevilmac** [comment]
You had to have removed the issue template and then copied in a crash log to make this issue. Follow the template that is provided.
