### ISSUE TITLE
Optimization of collision detection on slopes

### ISSUE THREAD

**Issue by VillagerGold** [TridentMC/ArchitectureCraft#132]
- The version of the mod you are using 3.108
- Your Minecraft version 1.12.2
- Your Forge version cleanroom-0.2.1-alpha
As the title suggests, ArchitectureCraft's slope collision detection uses stair collision detection instead of slope collision detection. For slope collision detection, you can refer to this mod
https://legacy.curseforge.com/minecraft/mc-mods/blockcraftery
https://github.com/MysticMods/Blockcraftery

**Comment by darkevilmac** [comment]
You'd need to show me the relevant code, but Minecraft uses AABBs for collisions. You can't rotate them without changes to the way the game handles collisions.

**Comment by VillagerGold** [comment]
In the main text, I have provided mods for optimizing collision detection. Please open the link to GitHub in the main text to see how to change the way the game handles collisions

**Comment by darkevilmac** [comment]
You provided an entire git repo which from what I can see also just uses standard collision boxes - it may be using more of them on a given slope but they're still not actually slanted. In addition, by increasing the amount of boxes on a given model you're potentially sacrificing performance when there's large amounts of those blocks in the world. For example, when there's rain in the game each rain particle performs a collision check on the top of a block, if I increased the "precision" of the fake angle on the collider then I've increased the amount of calculations required for every rain particle on every sloped block.

**Comment by VillagerGold** [comment]
Please use more collision detection, as performance is not an issue and I need a better gaming experience

**Comment by VillagerGold** [comment]
Can you tell me approximately when the version that solves this problem on Curseforge will be released? I can't wait anymore

**Comment by VillagerGold** [comment]
May I ask if you can reply to the above question, as the game I created requires this update

**Comment by knobsam** [comment]
With all due respect, this issue is closed and the author stated that "everything works as intended". /c

**Comment by VillagerGold** [comment]
@darkevilmac May I ask when will the ArchitectureCraft version 1.12.2 be updated? I am looking forward to the collision detection update

**Comment by darkevilmac** [comment]
@VillagerGold as mentioned by @knobsam - this is working as intended and I don't have any intention on implementing a change for the reasons mentioned above. Minecraft doesn't do well with highly precise collision and trying to fake it into working is out of scope for a mod that's primary focus is on decorations.

**Comment by VillagerGold** [comment]
> @VillagerGold as mentioned by @knobsam - this is working as intended and I don't have any intention on implementing a change for the reasons mentioned above. Minecraft doesn't do well with highly precise collision and trying to fake it into working is out of scope for a mod that's primary focus is on decorations.

It's okay, you can refer to the GitHub link at the beginning and write collision detection like blockcraft. When will the update for version 1.12.2 be released

**Comment by VillagerGold** [comment]
@darkevilmac My friend has built ArchitectureCraft for Blockcraft collision detection. You can directly use the source code to optimize the collision detection of ArchitectureCraft. If possible, you can set my friend as a contributor
https://github.com/spocel/ArchitectureCraft
