### ISSUE TITLE
Crash, cannot open map anymore

### ISSUE THREAD

**Issue by winsrp** [TridentMC/ArchitectureCraft#14]
was putting the very first window frame made out of acacia over a sandstone wall (with a 3x2 window hole) now it crashes every time I load the map. The frame was being put at the lower left side of the window if that helps.

Mod version 1.12-1.20
Minecraft 1.12.2
Forge 1.12.2-14.23.0.2528

https://pastebin.com/iiVVfwGQ

**Comment by darkevilmac** [comment]
Remove optifine.

**Comment by asiekierka** [comment]
(Or, first, just update Forge and OptiFine. A lot.)
