### ISSUE TITLE
Model Loading Errors - 1.12.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TridentMC/ArchitectureCraft#16]
https://gist.github.com/P3rf3ctXZer0/f97114c01c2d642f43d1247e64cef771

Everything I can report is located in the gist post.

**Comment by darkevilmac** [comment]
These errors are just because of the way the mod handles models and such. Not a big deal and it doesn't change how the mod works.

Kind of surprised forge doesn't log that stuff with Level.WARN.
