### ISSUE TITLE
Issues with block colors and certain blocks. (Flat Colored Blocks and Forestry So Far)

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TridentMC/ArchitectureCraft#17]
::BASIC INFO::

Version of the mod you are using ~ architecturecraft-1.12-2.62.jar
Minecraft version ~ 1.12.2
Forge version ~ 1.12.2 - 14.23.1.2555

::BASIC INFO::
+++++++++++++++++++++++++++++++++++++++++++++++
::LOGS::

Client Early Startup
https://gist.github.com/P3rf3ctXZer0/9701e46eee2453709e30f26da70eff5e

Latest
https://gist.github.com/P3rf3ctXZer0/df9cfd6a9e0d38b50f193b8f91f34405

Client Latest
https://gist.github.com/P3rf3ctXZer0/78e29c96e1081e6376af67bb64bb125e

::LOGS::
++++++++++++++++++++++++++++++++++++++++++++++
::IMAGES::
![2018-01-02 07_01_42-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/34484839-28aab520-ef8d-11e7-8f72-b62b60369970.png)
![2018-01-02 07_02_54-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/34484840-28b78ad4-ef8d-11e7-9367-9a5e3bc3ea12.png)
::IMAGES::

::NOTES::
I didn't screenshot everything but basically it seems everything past slope would not register colors and attributes as detected. I do have foamfix but I only use de-duplication function - I disabled all other functionality.

**Comment by asiekierka** [comment]
Someone didn't proxy their tint handler...?

**Comment by P3rf3ctXZer0** [comment]
What does that mean? Can you explain a bit deeper please?

**Comment by asiekierka** [comment]
@P3rf3ctXZer0 The mod author will know what I mean, don't worry, it's not your fault

**Comment by P3rf3ctXZer0** [comment]
Okay ^_^ at any rate let me know when you commit a fix I will be happy to try and break it ;) through testing.

"Unrelated"
"Could you let LexManos know that somewhere along the lines of forge releases beyond 555 he broke chest manager it creates a severe bug with some mods - I have been unable to pinpoint which mods cause it seems like an oddly speratic bug. Lex won't talk to me because 2 years back I got in huge fight with him over NotEnoughIDs mod by @Fewizz."

So far I know I noticed when little tiles or creative core rather is installed it can be triggered.

**Comment by asiekierka** [comment]
Figure out the exact build number.

**Comment by darkevilmac** [comment]
Are you using a dev build from ci or are you still using the curse builds. The curse builds haven't been updated with tint handlers at all.

**Comment by P3rf3ctXZer0** [comment]
I am using the ci build because I only test with latest versions located here 
https://ci.elytradev.com/job/elytra/job/ArchitectureCraft/job/1.12/

**Comment by darkevilmac** [comment]
Fixed in the most recent CI builds.
