### ISSUE TITLE
Inner corner block recipe requirment not accurate?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TridentMC/ArchitectureCraft#18]
Minecraft Version 1.12.2
Forge Version 14.23.1.2555
Mod Version architecturecraft-1.12-2.62.jar

I am not sure why but I am unable to craft roof inner corner

Client Latest
https://gist.github.com/P3rf3ctXZer0/ec7c3508f35b01c37b3a35831885c696

Latest
https://gist.github.com/P3rf3ctXZer0/26413930211e659674a4bb982dccecfc

![2018-01-02 08_12_44-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/34486313-e4be24e8-ef94-11e7-96ad-75879de71151.png)

**Comment by P3rf3ctXZer0** [comment]
Um okay so that is interesting but apparently
![2018-01-02 08_16_40-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/34486414-80380bdc-ef95-11e7-91ac-fd60225efd89.png)
 I was able to after I had 4 blocks of a type in there.

**Comment by darkevilmac** [comment]
the recipe is accurate this is an issue with the gui not checking stack sizes correctly by the looks.

**Comment by P3rf3ctXZer0** [comment]
okay just reporting :)

**Comment by P3rf3ctXZer0** [comment]
Similar issues with stairs. 
![2018-02-01 12_40_52-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/35696588-7f728cd4-074d-11e8-81c9-2f428892f409.png)
