### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by piemz** [TridentMC/ArchitectureCraft#19]
Hello, 
I have a 1.10.2 server modded with the last "official" version of ArchitectureCraft (1.7.3) and I **really** would like to update to 1.12.2 for technical problems. So your porting project is crucial for me. 
My problem is that, differently from my previous update from 1.8.9 to 1.10.2, your ArchitectureCraft version is not backward-compatible: so all the blocks I placed with AC would now look like basic architectural blocks (wooden roof). 
My 1.12.2 Forge version is 14.23.1.2555. 
Unfortunately I am not able to understand anything out of this: that is why an intervention from you could save me and would be sincerely appreciated.

Thank you very much in advance for your attention.
Greetings from Italy,
mazza 
![server](https://user-images.githubusercontent.com/35231440/34681643-d05266b0-f49c-11e7-8913-fea3701b305a.jpg)

**Comment by wussler** [comment]
Hi Piemz,
I found a workaround for the porting, with a simple python3 script, using NBT (https://github.com/twoolie/NBT)
```Python
import os, sys
from nbt import *

path = sys.argv[1]
listing = os.listdir(path)
for infile in listing:
    region_file = os.path.join(path, infile)
    print ("Processing region: " + region_file)
    region_data = region.RegionFile(region_file,'rb')
    chunks_meta = region_data.get_metadata()
    for chunk in chunks_meta:
        blocks = region_data.get_blockdata(chunk.x, chunk.z)
        blocks = blocks.replace(b'\rgcewing.shape', b':minecraft:com.elytradev.architecture.common.tile.tileshape')
        region_data.write_blockdata(chunk.x, chunk.z, blocks)
```

It's a terrible hack that I used to port my server, hoping it will solve your problem as well.
Greetings from Austria,
Aron Wussler

**Comment by piemz** [comment]
Thank you comrade!

https://youtu.be/JvXv4FcUzJ0

**Comment by darkevilmac** [comment]
Its due to a change in the tile id, I'll see if I can add a converter.

**Comment by darkevilmac** [comment]
Fixed https://github.com/elytra/ArchitectureCraft/commit/fab80f1ed3c25756f812bccd8225625fccedc720
