### ISSUE TITLE
NullPointerException: Updating screen events 

### ISSUE THREAD

**Issue by Ricket** [TridentMC/ArchitectureCraft#21]
architecturecraft-1.12-1.20.jar

MC 1.12.2

Forge 14.23.1.2601

Crash report: https://gist.github.com/Ricket/a4d008dcbdb1cf5c0150278079248dab

Same as #13 but you dismissed it. We've hit it twice now.

**Comment by darkevilmac** [comment]
Duplicate of #7 this has already been fixed.
