### ISSUE TITLE
Bug - 90% of the Binnies Forestry Addon Does Not Work and The Ones That Do Are Textureless

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TridentMC/ArchitectureCraft#22]
So I am using 
Alpha 1.12-2.68
![2018-02-01 12_35_57-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/35696389-f4a97504-074c-11e8-8e76-88b9a1ff0589.png)
![2018-02-01 12_35_30-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/35696390-f4bb63b8-074c-11e8-85c6-4c63a5be3fd6.png)
![2018-02-01 12_35_21-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/35696391-f4cef842-074c-11e8-8327-3f4b4ee2ebc3.png)
![2018-02-01 12_30_45-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/35696392-f4e09944-074c-11e8-84c2-abc4c1d378dd.png)

**Comment by exaskye** [comment]
Binnie's mods use tile entities to define the color of a given block, since there's such a ridiculous amount of variants. ArchitectureCraft is not aware of this variant information, but probably could be made aware.

**Comment by P3rf3ctXZer0** [comment]
@unascribed As Always thank you :D
