### ISSUE TITLE
Idea - Doors

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TridentMC/ArchitectureCraft#23]
Would be nice to have certain textures I noticed minecraft truly lacks doors.

**Comment by UnixRonin** [comment]
Have you looked at some of the existing doors mods such as Malisis Doors?

**Comment by falkreon** [comment]
Do you mean a door which is functionally identical to wooden door but can take any texture? How specifically does Minecraft lack doors? Let's pin this idea down so it can be properly considered :)

**Comment by UnixRonin** [comment]
Carpenter's Blocks used to have a Carpenter's Door that you could do that with, but mineshopper is **still** trying to get it updated.  He's had to rewrite it totally from scratch.

**Comment by P3rf3ctXZer0** [comment]
So - it makes sense to have the feature attached to one mod or else you get duplicate Ideas and sometimes recipes.
