### ISSUE TITLE
Error. Exception loading model for variant [MC1.12.2]

### ISSUE THREAD

**Issue by kellixon** [TridentMC/ArchitectureCraft#26]
Minecraft: 1.12.2
Forge: all (last 14.23.2.2637)
ArchitectureCraft 2.68
Lines:
10825
10848
10923
10946
Debug Log - https://drive.google.com/open?id=17dCrv1l_taOd9Js8wWa6RZbId6PPamuF

**Comment by darkevilmac** [comment]
Looks like that link doesn't work anymore, I'll reopen the issue if you happen to have that log laying around somewhere.

**Comment by kellixon** [comment]
13527
13550
13573
13596
https://gist.github.com/kellixon/e6a09ef2cd3286735906e4ab9a08b173
