### ISSUE TITLE
Sawbench not working with glass

### ISSUE THREAD

**Issue by SergeantTibbs** [TridentMC/ArchitectureCraft#29]
The title pretty much says it all.  I don't have an error log because the glass just doesn't show up in the output section of the sawbench when I put the block of glass in the input.  It worked before because I made a huge glass ceiling.  When I went to make more glass to do some repairs it was surprising to have it not work.

- The version of the mod I'm using 1.7.1
- My Minecraft version 1.7.10
- I'm using Technic Launcher and the GT New Horizons (version 2.0.3.0) modpack

**Comment by exaskye** [comment]
This repository is a fork of ArchitectureCraft updated to 1.12. We cannot support the 1.7 version. If this problem still occurs in the fork, then we can reopen the issue.

**Comment by falkreon** [comment]
The original (1.10 and earlier) author can be found over here: http://www.cosc.canterbury.ac.nz/greg.ewing/minecraft/mods/ArchitectureCraft/

**Comment by SergeantTibbs** [comment]
Understood!  Sorry for the confusion, and thank you for the redirection.
