### ISSUE TITLE
Mod Compat request: Fruit Phone

### ISSUE THREAD

**Issue by BBoldt** [TridentMC/ArchitectureCraft#3]
It would be nice if fruit phones would be able to display the model and block type of architectural blocks being viewed.

![](https://i.imgur.com/UQFN6h2.png)

**Comment by exaskye** [comment]
> tfw an elytra mod isn't compatible with fruit phone

**Comment by darkevilmac** [comment]
but like, i have to make the mod not suck first.

**Comment by darkevilmac** [comment]
![](https://i.imgur.com/BYoJPqO.png)

**Comment by BBoldt** [comment]
Looks good. 

The only thing else that I can think of that would be good in fruit phone support is stating the model type.

ie: "Architectural Slope" instead of "Architectural Block"
"Spherical Abomination" instead of "Architectural Block"
