### ISSUE TITLE
Updated:  Wooden items vanish when broken

### ISSUE THREAD

**Issue by UnixRonin** [TridentMC/ArchitectureCraft#33]
architecturecraft-1.12-2.68
forge-1.12.2-14.23.2.2654

Window frames vanish when broken, whether by hand or with an axe or chisel.  No error is logged.  Just **poof**, gone.  This is a regression from GregT's 1.10.2 version.

**Comment by UnixRonin** [comment]
Update:  I have discovered that this is not **just** window frames.  It appears to be **any** architectural part **cut from any wood.**  Cut from stone or metal, and if you mis-place a part and break it, the original part drops and you can just re-place it correctly.  But if it was cut from wood, **POOF!**  Break it and it's gone.

**Comment by Xenoamor** [comment]
I found you can break the wooden items with a pickaxe and it will drop the item. Although it will be very slow

**Comment by Sewef** [comment]
Update : you can get AC shapes only with pickaxe. Breaking a dirt shape with shovel does nothing too.
