### ISSUE TITLE
[Suggestion] Add Window box

### ISSUE THREAD

**Issue by winsrp** [TridentMC/ArchitectureCraft#34]
So how about a nice external window box that we can put flowers in? Something like a minecraft pot that takes the texture of the block in the bench, but sticks to the outside of the window with the length of a block.

There is also that other decoration piece that goes in place of the window box that is only decor not for flowers, but I have no idea how it is called.

**Comment by falkreon** [comment]
The thing under the window on the outside is an "exterior moulding". It's also not very visually distinct from a soffit, so the block might wind up used both under windows, and over windows and doors. I like this idea.
