### ISSUE TITLE
1.12-2.68:  Architecturecraft blocks spontaneously reverted to roof tiles

### ISSUE THREAD

**Issue by UnixRonin** [TridentMC/ArchitectureCraft#37]
Mod:  architecturecraft-1.12-2.68
MC:  1.12.2
Forge:  1.12.2-14.23.3.2677
Java:  JDK 1.8.0.172

I ran into a bizarre occurrence last night in which all Architecturecraft blocks within a single chunk (railings, window frames, cornices being used as window ledges, columns, metopes) spontaneously reverted to oak roof tiles.  I have no idea whatsoever what triggered it.  There is absolutely nothing of interest or even relevance in the log except for the line at 23:44:46 below:

[23:42:08] [Server thread/INFO] [STDOUT]: [thaumcraft.common.lib.research.ScanSky:onSuccess:83]: CEL_803_Moon3
[23:44:46] [Server thread/INFO] [ArchitectureCraft]: Loading and caching OBJSON model shape/roof_overhang.objson
[23:47:01] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: CaerMaster lost connection: Disconnected

The shape/roof_overhang was not in the affected chunk.

Screen shots illustrating the issue:

[As initially observed](https://www.caerllewys.net/public/minecraft/2018-05-22_23.43.08.png)
[View showing chunk boundaries](https://www.caerllewys.net/public/minecraft/2018-05-22_23.46.01.png)

After restarting server and client, all of the affected blocks reverted to what they originally were.

**Comment by Dranemra** [comment]
I'm experiencing this as well. I recall it having to do with another mod conflicting. At one point in the past, I managed to fix it... but some mods have changed since, and it appears the fix no longer works. 

This has been an outstanding issue since May, any further info on it?

**Comment by miiichael** [comment]
I've had this happen occasionally too (1.12-3.80 on forge 1.12.2-14.23.5.2795 and a bunch of other mods), but believe it's only a rendering issue - the blocks don't actually transmogrify, and disconnecting and reconnecting the client seems to suffice to return things to normality.
