### ISSUE TITLE
Can,t craft Some blocks in the sawbench

### ISSUE THREAD

**Issue by thecrescentkid** [TridentMC/ArchitectureCraft#38]
![2018-06-09_18 27 41](https://user-images.githubusercontent.com/37762002/41196973-d6aa4188-6c13-11e8-9937-b907fbc3f692.png)
![2018-06-09_18 28 55](https://user-images.githubusercontent.com/37762002/41196975-d6ee4a7c-6c13-11e8-97ae-888c4491ac5d.png)
![2018-06-09_18 29 21](https://user-images.githubusercontent.com/37762002/41196976-d7342d58-6c13-11e8-9b0f-1f275040ddf8.png)

**Comment by falkreon** [comment]
Working as intended. You have one block of material in "2 makes 3", "3 makes 4", and "2 makes 3" recipes. You need to put two or three blocks into the bench for those to make anything.
