### ISSUE TITLE
Server Loading issues

### ISSUE THREAD

**Issue by NLBlacky** [TridentMC/ArchitectureCraft#40]
So after we restart our server and it shows online in the server list and you can actually join it, you time out. This keeps happening for the first ~3 minutes. When watching console, console is frozen.

After 3 minutes, the following messages popup in console. It seems after the server is online, it takes around 3 minutes to load in those structures.

https://image.ibb.co/eZLmd9/j84kyl7mhag11.png
https://gist.github.com/NLBlacky/2b30b00ad79fb6d94ad385c99cbac842
The log pasted here was a random taken log since this issue happens at every startup. In this example it took less than 2 minutes before the server was responding, but this can be alot longer in some cases.

I'm wondering if there is anyone else having this issue and know how to solve this without disabling ArchitectureCraft?

I didn't had this when the server was empty, it came later. 
Server is running Revelation 2.3, Minecraft 1.12.2 and Forge 14.23.4.2750-universal.

**Comment by darkevilmac** [comment]
Have you confirmed the issue is with ArchitectureCraft? Does the issue stop when you remove the mod?

I've done some tests locally and some models can take a bit of time to load, but the longest time I can measure has been 9ms for a model. When I calculate the total amount of time for every model I get about 175ms. Not sure what's causing the issue but it seems unlikely that it has much to do with the model loading.

**Comment by NLBlacky** [comment]
When I disable the mod, the issue is gone. Loading the textures/models seems to be the issue. 
I do not know what causes it. Does it have too many of those items in the server? (even though when those items are not used much tbh. Max 10 per item are in the server of those in the console).

It is annoying that we've to wait a extra 1-3 minutes for the server to be joinable after it is up.

**Comment by darkevilmac** [comment]
@NLBlacky Can you test with this jar and provide the server log?

https://ci.elytradev.com/job/elytra/job/ArchitectureCraft/job/1.12/67/artifact/build/libs/architecturecraft-1.12-2.73.jar

**Comment by NLBlacky** [comment]
No I cannot do that since it is on a live server with players and I do not have the hardware left to make a test server. Even if that would solve the issue I still cannot update it since it would count as a different modpack and I want to keep the original modpack.

I think it is better to just close this ticket. It is a month old, I've accepted that the restarts take a few minutes longer due loading some textures from your mod, I also no longer have the available time to do testing and since the server is live already I will not put it down for testing.

Thanks for your responses though.
