### ISSUE TITLE
Prevent snow and torch placement

### ISSUE THREAD

**Issue by Sewef** [TridentMC/ArchitectureCraft#41]
Hello there.
I'm making outdoor stuff on snowy moutain, and the custom stairs and balustrades looks weird with snow on them.
As the vanilla stairs, is it possible to prevent snow formation and torch placement on ArchitectureCraft's blocks ?

Thanks c:

**Comment by Xenoamor** [comment]
+1. This issue also happens with sloped roofs

**Comment by Xenoamor** [comment]
I've made a pull request that should fix this https://github.com/elytra/ArchitectureCraft/pull/44

**Comment by Sewef** [comment]
I love you.
