### ISSUE TITLE
IndexOutOfBoundsException - Crash

### ISSUE THREAD

**Issue by lays24mc** [TridentMC/ArchitectureCraft#42]
Game crashed and create this crashlog: https://pastebin.com/sueztupj

Minecraft 1.12.2
Forge 2760
AC Version: architecturecraft-1.12-2.68.jar

**Comment by darkevilmac** [comment]
Can you provide steps to reproduce this bug? What block where you using? Did it happen immediately after you placed the block? Was this on multiplayer or singleplayer?

I need something to go off of besides the log.
