### ISSUE TITLE
Crash on block break in survival

### ISSUE THREAD

**Issue by gamefreq0** [TridentMC/ArchitectureCraft#43]
ArchitechtureCraft version 2.68
Minecraft 1.12.2
Forge 14.23.4.2725
[Log](https://gist.github.com/gamefreq0/12a0a2441e1641252391c8489d3df4c1)

When attempting to break any blocks made from Ironwood Planks (from the Primal Core mod) run through the Architect's Table, if you're in survival mode, the game crashes. I'm fairly certain it also affects Corypha, Yew, and Lacquer planks, though I haven't yet tested this. I can also test some other blocks to see if they are affected as well, if you would like. The crash doesn't affect creative mode, likely because hardness doesn't get checked there. If this is an issue with Primal Core, could I request a config to blacklist blocks from the Architect's Table?

EDIT: I further tested some other blocks, including vanilla Oak Planks, PrimalCore Bluestone, and PrimalCore Corphyra Planks (the spelling is inconsistent within the mod). Breaking these in survival worked, with the exception of the latter (causing the same crash stacktrace), which seems to indicate it's an issue with those 4 specific PrimalCore wood types, leading me to believe this might be an issue with PrimalCore and not this mod.

**Comment by darkevilmac** [comment]
Definitely related to PrimalCore, pushing a quick fix anyway.
