### ISSUE TITLE
Minor Issue - A single missing texture ; easy fix.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TridentMC/ArchitectureCraft#45]
Thanks for reporting an issue to an Elytra project!

When reporting an issue to an Elytra project, please make sure to include:

- The version of the mod you are using **architecturecraft-1.12-2.68**
- Your Minecraft version **1.12.2**
- Your Forge version 1.12.2 - **14.23.4.2764**
- The crash report or log, uploaded to gist.github.com
 **https://gist.github.com/P3rf3ctXZer0/8e7bc9a177e79c2aacda53db65d56d62**

**Comment by realTIMematrix** [comment]
Same Issue for me. Would like to know if this is important or not

**Comment by Sewef** [comment]
Welp, the only `__custitem__` occurence is here : https://github.com/elytra/ArchitectureCraft/blob/1.12/src/main/java/com/elytradev/architecture/client/render/RenderingManager.java#L399
I don't know what would happen with this line removed, tho.
