### ISSUE TITLE
Crash when running with OpenJdk8 with Openj9 instead of Hotspot

### ISSUE THREAD

**Issue by liketechnik** [TridentMC/ArchitectureCraft#47]
Version: Filename is architecturecraft-1.12-2.68.jar (from enigmatica expert 2: skyblock), the one I tested/created the report with (created a clean forge profile) is 1.12-2.51)
Minecraft version: 1.12
Forge version: 14.23.4.2751 (same happens with 'latest', e. g. 14.23.4.2765
Crash Report: https://gitlab.com/snippets/1758424

When running MC with OpenJDK8, based on  OpenJ9 (https://www.eclipse.org/openj9/) JIT instead of Hotspot, architecturecraft crashes (see crash report), although it's running fine with 'standard' Java. Is this an issue with architecturecraft or is the problem on my side because I run a different Java implementation? (note: Forge itself is running fine, it's only crashing with architecturecraft enabled)

From what I could see in the Crash-Log, it's an issue with how acraft uses reflection, or rather the difference between J9 and Hotspot only comes into play with the mod's use case of reflection.

**Comment by danielhuang** [comment]
This issue was solved in OpenJDK version 8u202.

**Comment by Dimentive** [comment]
This has been solved. This issue should be closed.

**Comment by liketechnik** [comment]
To be honest, I more or less forgot about this. Closing because it's fixed now.
