### ISSUE TITLE
Client crash 

### ISSUE THREAD

**Issue by Griefed** [TridentMC/ArchitectureCraft#49]
Mod Version: Alpha 1.12-3.80
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2768
Crash Report: https://pastebin.com/ejkThF0Y

Client crashed, server stayed up, when I went to my base in The End, which has lots of ArchitectureCraft blocks.

Hope this is of any use for you.

Cheers,
Griefed

**Comment by sh1kxrv** [comment]
UP
