### ISSUE TITLE
Major Request - Fine tune collision detection and rotation.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TridentMC/ArchitectureCraft#54]
Minecraft : 1.12.2
Forge: 1.12.2 - 14.23.5.2775
Mod Version: Alpha 1.12-3.80

Stair collision detection is a nightmare. Can you please fine-tune the way stairs are placed?

Please see the video.
https://youtu.be/ewgJfGH8ah0

**Comment by darkevilmac** [comment]
Preview rendering makes this less of a pain, no plans to rework any sort of placement logic.
