### ISSUE TITLE
More Roof Tiles that stretch over more than one block, for longer roofs/flatter angles

### ISSUE THREAD

**Issue by Griefed** [TridentMC/ArchitectureCraft#55]
Hello my lovely ArchitectureCraft devs.

If I may make a suggestion:
Could we have more, like the title says, Roof Tiles with flatter angles so we can build longer roofs?
Just like the arches that consist of multiple parts to build a whole, I would love to see something similar for the Roof Tiles.

I hope I explained my issue well. English isn't my first language, sorry.

Cheers,
Griefed

**Comment by miiichael** [comment]
I'd love to see this too, but am mindful of the explosion of different block shapes that would result, even without extra features such as overhangs. Rotating pieces to the desired orientation will also get more challenging (or maybe that's just me that already averages 15 rotations before it's in the position I wanted...). And of course I expect this will make the hip/valley DWIM magic excitingly complicated too.
![architecturecraft extra roof shapes](https://user-images.githubusercontent.com/4179353/51464347-4d474500-1da0-11e9-8889-402c50434ecd.png)

**Comment by pkej** [comment]
Try little tiles which can make slants at any angle. https://youtu.be/Bfg88rRNocA?t=15m25s
