### ISSUE TITLE
[Suggestion] Quarter block pieces

### ISSUE THREAD

**Issue by darthvader45** [TridentMC/ArchitectureCraft#57]
I'd like to suggest quarter blocks for addition to the mod, as when I build exterior walls for my buildings, there's always that one gap in the wall that I can't fix.  As a result, I can't get cladding all around the building.

**Comment by darkevilmac** [comment]
Nothing planned currently, maybe once the model system is rewritten/cleaned up.

**Comment by darthvader45** [comment]
Thanks.
