### ISSUE TITLE
Lag in Creative Tab and NEI

### ISSUE THREAD

**Issue by inf1425** [TridentMC/ArchitectureCraft#58]
- 3.80
- Minecraft 1.12.2
- Forge 14.23.5.2796

I get massive lag in JEI and the creative tab of architecturecraft. I checked my CPU usage, which was at 36% and my GPU usage, which was at 16%. I think the model format should be changed to .OBJ becuase this lag is not due to a bottleneck.

**Comment by Xenoamor** [comment]
It would make it a lot easier to add in new shapes/blocks which it currently isn't

**Comment by darkevilmac** [comment]
> I think the model format should be changed to .OBJ

That's a lot easier said than done, currently the mod is in a sort of frozen state until I can make a stable 1.13 build. I might make a fix or two for 1.12, but changing model formats won't be coming any time soon.

**Comment by Xenoamor** [comment]
I completely agree. I looked over the way it handles the 3d files and it's very very heavily baked into the code. You'd almost need an entire rewrite

**Comment by inf1425** [comment]
Could I get model files for all the blocks? I'll try making a obj loader.

**Comment by Xenoamor** [comment]
I could be wrong but when @darkevilmac took over development of the project he never got any 3d files for the blocks

**Comment by falkreon** [comment]
The original code darkevil inherited had an even more entrenched code-based model system, whose surface normals and lightmap UVs were in a really bad way. Forge already comes with a pre-rolled .obj model loader, which comes with a bunch of its own headaches (particularly when trying to replace two textures, as would be required for cladding support here). iirc someone has already generously donated new obj models (hi Meoil!), but you're right when saying it would require a near-total rewrite to incorporate them.

**Comment by inf1425** [comment]
I browsed through the code, it definitely needs a rewrite if an OBJ loader has to be implemented.

**Comment by Xenoamor** [comment]
Perhaps effort would be better spent making an obj to whatever format this uses converter?
