### ISSUE TITLE
Odd shadows with baked models.

### ISSUE THREAD

**Issue by darkevilmac** [TridentMC/ArchitectureCraft#6]
![](https://i.imgur.com/fgnemTd.png)

Shadows don't render correctly with the new baked model system, not sure why quite yet.

Only happens if there's a solid block below the shape (or above if the shape is inverted)

**Comment by P3rf3ctXZer0** [comment]
I would like to show that with latest fix release you gave me all angled blocks have a shadowed effect.

Specs Mods and Versions
https://gist.github.com/P3rf3ctXZer0/b0500b4decdc780b85a98f57008c6090

Here is an example please note all images of ledges are used out the white chiseled block.

On a side note what do think of server hub structure so far?
![2017-09-25_17 29 38](https://user-images.githubusercontent.com/10351221/30834239-263c3d64-a207-11e7-979d-931dcfc98f79.png)
![2017-09-25_17 29 43](https://user-images.githubusercontent.com/10351221/30834240-2648b68e-a207-11e7-9260-34618afb46e9.png)

**Comment by darkevilmac** [comment]
I can't reproduce this in my test world.

![](https://i.imgur.com/iSjTRRs.png)

**Comment by P3rf3ctXZer0** [comment]
I will try and look at things. By chance do you have foamfix enables?

**Comment by falkreon** [comment]
![image](https://user-images.githubusercontent.com/1153007/30994888-a826e96c-a484-11e7-9641-7855f61ae1a3.png)

So I managed to reproduce this...
Forge 14.22.1.2484 and ArchitectureCraft 2.6.1 built straight from the repo. Some errors about lanterns but nothing that should be causing this.

**Comment by falkreon** [comment]
![image](https://user-images.githubusercontent.com/1153007/30995147-42099a2e-a486-11e7-96cd-d0d17ba63b0f.png)
The plot thickens?!?

**Comment by darkevilmac** [comment]
With blockcolors I'm just setting the color directly from the int provided, I think there's a special cased int.

**Comment by falkreon** [comment]
I don't *think* this is a blockColor issue - materials are engination dolomite and vanilla oak planks (with chisel smooth plank blocks for color comparison), neither of these use block colors.

**Comment by darkevilmac** [comment]
Is this with the most recent builds or the baked model experiment?

**Comment by P3rf3ctXZer0** [comment]
Mine is with the fixed version you gave me. Did you put out another one?

**Comment by falkreon** [comment]
I pulled 06625ec (most recent commit) and built it locally from the main branch, so I don't think this includes any really experimental code.

**Comment by Nitess** [comment]
What's wrong with the texture? The texture behind is half normal
ArchitectureCraft 2.61
Forge 14.23.0.2552 
![2017-11-25_03 19 26](https://user-images.githubusercontent.com/30369743/33225803-97e046f6-d18f-11e7-9e63-57d559ef03cd.png)

**Comment by Nitess** [comment]
and empty mine from forge 14.23.0.2551 and ArchitectureCraft 2.61
![2017-11-25_03 36 16](https://user-images.githubusercontent.com/30369743/33225933-4adec780-d192-11e7-853e-1db73258c169.png)
![mine](https://user-images.githubusercontent.com/30369743/33225934-4d1aa3fc-d192-11e7-9448-6841ea31c3f0.png)

**Comment by P3rf3ctXZer0** [comment]
I will test latest version unless net neutrality is removed ... then I will not be back once Xfinity makes their shady moves.

**Comment by Nitess** [comment]
In versions before 2.57 Build #52 no bugs with render.
Before you add "Add colour mult to render code."

**Comment by P3rf3ctXZer0** [comment]
OH YEAH THAT WAS WHAT I MEANT TO REPORT XD thanks for rediscovering the bug timing XD @Nitess

**Comment by P3rf3ctXZer0** [comment]
![2018-01-02 08_00_23-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/34486189-2c6f8d3c-ef94-11e7-8d8e-424ec9ff4a57.png)
Okay well I made windows with the purple Terracotta blocks and rather than the frame being purple it has an oddly stretched  partial texture 

Minecraft 1.12.2
Forge Version 14.23.1.2555

Mod Version architecturecraft-1.12-2.62.jar

::Logs::

FML Client Latest
https://gist.github.com/P3rf3ctXZer0/51de8b6b73e91451b985572ae4c3f5ee

Latest
https://gist.github.com/P3rf3ctXZer0/d366ee0d82024e5223946f00314e5e2c

**Comment by darkevilmac** [comment]
This should all be resolved in the current ci builds, closing for now. Will reopen if the issue persists.
