### ISSUE TITLE
[Suggestion] Right clicking on a window frame with a glass pane should not consume the glass pane

### ISSUE THREAD

**Issue by TheRandomLabs** [TridentMC/ArchitectureCraft#60]
Currently, right clicking on a window frame with a glass pane causes the glass pane to be consumed. I've tested this on [1.12-3.80](https://minecraft.curseforge.com/projects/architecturecraft-elytradev/files/2624386).

**Comment by Sewef** [comment]
Uuuuh, it makes sense to me o_ô
You place the glass pane in the window frame, no?

**Comment by TheRandomLabs** [comment]
When building in creative mode, it is more convenient if the glass pane is
not consumed so that it does not have to be restocked. The current behavior
is not consistent with everything else in creative mode, for example, spawn
eggs are not consumed when they are used and blocks are not consumed when
they are placed.

**Comment by Sewef** [comment]
You're right.

**Comment by Sewef** [comment]
https://github.com/elytra/ArchitectureCraft/blob/1.12/src/main/java/com/elytradev/architecture/common/tile/TileShape.java#L232
I guess this code is not working anymore. Maybe change for `if !player.isCreative()`?

**Comment by TheRandomLabs** [comment]
I usually see `player.capabilities.isCreativeMode` used.
