### ISSUE TITLE
.lang files only contains texts for Sawbench ingredients and tools (no shapes, also "%s makes %s" in the GuiSawbench)

### ISSUE THREAD

**Issue by PolyacovYury** [TridentMC/ArchitectureCraft#62]
Mod version: 2.68.

Well, the title has it all.
Imagine a bunch of Russian users stuck with English hard-coded shape names trying to communicate using those.

P.S. The mod needs to stop using TEs in 1.13 in favor of blockstates, since they are now stored as-is, can be arbitrarily large and don't lag the game as much.

**Comment by darkevilmac** [comment]
I'll take a look at the lang files, TEs will still be used in future versions though. There's still a lot of data that gets stored for each block in the world, if I just used block states then I would literally be doubling the amount of block states that the game has to register. Tiles are relatively cheap if they don't tick, all they take is a bit of memory usage.

**Comment by darkevilmac** [comment]
https://github.com/TridentMC/ArchitectureCraft/commit/1c3445ddf3ce591aa5620ac8e6c7b4bd4cdc412b#diff-40245bfd67f7ceca7b24446fe40f9cc0

done, only took like 11 months.
