### ISSUE TITLE
Blocks end up with the wrong materials

### ISSUE THREAD

**Issue by brisingraerowing** [TridentMC/ArchitectureCraft#63]
Forge Version: 14.23.5.2811
MC: 1.12.2
ArchitectureCraft: 3.80

No crash log.

I was using Quark's Polished Stone for a build, and made some into stairs with AC. When walking on those stairs, they acted like dirt with the sound (and Dynamic Surroundings considered them dirt for footprints). This is kind of annoying.

**Comment by brisingraerowing** [comment]
Is this in a released build? I am still having this issue with various materials (currently only tested planks and logs).

**Comment by Ezoteric** [comment]
I used lastest version and i saw that the vanilla grass stairs get a cactus green dirt skin and when in hand it shows a dirt stairs.

So i some are still wrong :(
