### ISSUE TITLE
make ArchitectureCraft blocks seal air for AdvancedRocketry builds

### ISSUE THREAD

**Issue by ben-mkiv** [TridentMC/ArchitectureCraft#64]
Hi, would be great if you could integrate support for AdvancedRocketry, so that the ArchitectureCraft blocks are AirSealed.

Its pretty easy as the mod only has one block class from what i can tell. (Couldnt setup a dev workspace as multiple dependencies failed to download (e.g. openeye, elytra-concrete)

In your mods init method do something like this after the shape block got registered
```java
if(Loader.isModLoaded("advancedrocketry")){
    zmaster587.advancedRocketry.api.AdvancedRocketryAPI.atomsphereSealHandler.addSealableBlock(CONTENT.blockShape);
}
```

in your build.gradle the api can be pulled from curseforge marven
`deobfCompile "advanced-rocketry:AdvancedRocketry-1.12.2-1.5.0:127:deobf"` as dependency

and this maven in your repos
```
maven {
        name = "CurseForge"
        url = "https://minecraft.curseforge.com/api/maven/"
    }
```

if you're confused you can take a look on how its done in OpenSecurity to register the NanoFog Block
https://github.com/PC-Logix/OpenSecurity/blob/1.12.2/build.gradle
https://github.com/PC-Logix/OpenSecurity/blob/1.12.2/src/main/java/pcl/opensecurity/OpenSecurity.java#L105

**Comment by ItsAMemeMario** [comment]
I was looking for the reason why my space station wouldn’t seal and this seems to be it. I really hope this catches the mod dev’s attention

**Comment by CalmBit** [comment]
This seems to be an issue with their mod, not this one. Requiring an API call for basic compatibility with the mod seems completely unwarranted. Sorry.

**Comment by ben-mkiv** [comment]
ArchitectureCraft is returning notSolid() or rather false for isFullCube() so how should a 3rd party mod know if that block could seal an air space?

**Comment by darkevilmac** [comment]
A dependency on another mod's API is not the way to resolve this, they should have a configuration option.

**Comment by ben-mkiv** [comment]
They have a config, but adding support in your mod just makes it more user friendly. Most players aren't aware of how to deal with configs neither what block names to put in

**Comment by CalmBit** [comment]
User friendliness is not a use case for a custom API for one particular mod. It is not on us to make everything work perfectly with any particular mod when perfectly valid and easy solutions exist. Modpacks are typically full of custom configuration to make mods work together _better_.

Configuration options are not hard, and if they _are_ because of bad design, then that's _again_ not on us, as we didn't design the rocketry mod. 

Yes, we don't return `isFullCube` - most of these blocks...aren't full cubes?

**Comment by ben-mkiv** [comment]
just adding architecture craft to the config is a bad choice because it would seal for every block

mod integration could solve this:
Sealed:
![](https://i.imgur.com/yzQMyt8.png)
not sealed:
![](https://i.imgur.com/3TXRg1N.png)

Blaming it on AdvancedRocketry or calling it wrong designed is wrong.
