### ISSUE TITLE
Incompatability with Shaders

### ISSUE THREAD

**Issue by 18aidanme** [TridentMC/ArchitectureCraft#66]
1.12.2
Alpha 1.12-3.80
Forge 14.23.5.2836
Shader BSL V.71

![2019-04-16_16 26 30](https://user-images.githubusercontent.com/2945572/56250293-9f80c500-6074-11e9-8c89-fad1f01b67f7.png)
![2019-04-16_16 26 26](https://user-images.githubusercontent.com/2945572/56250309-a6a7d300-6074-11e9-91ea-5eeeceabb637.png)

The ArchitectureCraft blocks are a lot darker in comparison to all the other blocks, I've combed the shader settings for a possible fix but have yet to find anything, the issue persists in all the other shaders I've used.

**Comment by darkevilmac** [comment]
A lot of this is down to the actual shapes of the blocks not falling in line with what a lot of shaders expect. No fix currently planned, but this may end up behaving better when I rewrite the render code.
