### ISSUE TITLE
Cladding Problem

### ISSUE THREAD

**Issue by donkeyrat** [TridentMC/ArchitectureCraft#68]
version of the mod: 3.80
version of minecraft: 1.12.2

My problem is that cladding always crashes my game. I put it in my inventory in the creative menu, my game dies. I put it in my inventory through the crafting bench, my game dies. I drop it on the floor, my game dies. I've tried removing the model from the files but it didn't fix the issue.

**Comment by darkevilmac** [comment]
This has been fixed in the newest build, I've uploaded it to CurseForge so it should be available within the next day or so.
