### ISSUE TITLE
Glitching blocks!

### ISSUE THREAD

**Issue by iInjection** [TridentMC/ArchitectureCraft#71]
Hello, 

attatched you can see a Video reference to the problem we have.

Since we cant figure out that it has to do something with a setting I want to know if this is already an issue. 

- The version of the mod you are using: 3.80
- Your Minecraft version 1.12.2
- Your Forge version 14.23.5.2838
[Video.zip](https://github.com/TridentMC/ArchitectureCraft/files/3245007/Video.zip)
- The crash report or log, uploaded to gist.github.com (.zip with a Video of the issue)

**Comment by iInjection** [comment]
[Video.zip](https://github.com/TridentMC/ArchitectureCraft/files/3245010/Video.zip)

**Comment by TheLimmo** [comment]
I have this problem, do you done she? What resourspack do you use?

**Comment by iInjection** [comment]
My friend was the one having problems; sphax purebd craft x128.

Am Do., 4. Juli 2019, 13:48 hat TheLimmo <notifications@github.com>
geschrieben:

**Comment by darkevilmac** [comment]
I've only had this problem myself when Optifine is installed. Optifine does some weird things to the render pipeline and ArchitectureCraft doesn't cooperate with that. If you don't have optifine then make another comment and I'll re-open the issue and take another look. Thanks.
