### ISSUE TITLE
[Feature] Arch: Inner and Outer corners

### ISSUE THREAD

**Issue by knobsam** [TridentMC/ArchitectureCraft#76]
Hello,

it would be really nice to have matching inner and outer arch corners for building arch tunnels going around corners and not only straight. I'm thinking of vertical versions (Diameter Part A, Part B) and horizontal ones (Diameter Part C, also connecting around corners or "junctions").

I'm not aware of how much work it would be to implement these block, but I would really appreciate the work.

Best regards,

Samuel

**Comment by CalmBit** [comment]
New blocks are not being considered at this time. Sorry.
