### ISSUE TITLE
Forge 1.15.2 is now stable - Please update my favorite mod of all time <3

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TridentMC/ArchitectureCraft#77]
Thanks for reporting an issue to an Elytra project!

When reporting an issue to an Elytra project, please make sure to include:

- The version of the mod you are using (e.g. 2.0.0a4) Invisible
- Your Minecraft version (e.g. 1.11.2) 1.14.4
- Your Forge version (e.g. 13.20.0.2252) 1.14.4 - 28.1.0 recommended build
- The crash report or log, uploaded to gist.github.com
  (e.g. https://gist.github.com/unascribed/09ec875df0cc830df1116559f4adb333) Invisible

![2019-09-12 19_46_01-Minecraft Forge](https://user-images.githubusercontent.com/10351221/64831308-c3502480-d59a-11e9-967c-95cfc4dce0d7.jpg)

**Comment by P3rf3ctXZer0** [comment]
I await the update with bated breath.

**Comment by P3rf3ctXZer0** [comment]
![image](https://user-images.githubusercontent.com/10351221/83223431-6b654800-a140-11ea-8df9-701ffafa0325.png)

**Comment by CalmBit** [comment]
Unfortunately, the mod author does indeed have real responsibilities to take care of before updating this mod. He is _aware_ of the fact Forge is updating, and he is _aware_ of the fact there are stable versions out. What you might not be aware of is that between versions 1.12 and 1.15, _many, many_ things have changed under the hood. Please be cognizant of the fact that despite this being your favourite mod, this is also the work of one person, maintaining a complicated mod and code base, all for free. Your interest is appreciated, and warranted even, but _please_ do not continually ask for mods to update. Thank you.

**Comment by P3rf3ctXZer0** [comment]
Trust me I understand but CalmBit I have seen many great mods since 1.6.4 die. I don't want this to be one. Since I cannot code I cannot up date it myself. I would even be will to pay 60 USD to a modder willing to update this mod.
