### ISSUE TITLE
Dark architecture blocks with shaders

### ISSUE THREAD

**Issue by LLIYXOB** [TridentMC/ArchitectureCraft#78]
- Mod version: Alpha 1.12_3.98
- Minecraft version: 1.12.2
- Forge version: 14.23.5.2838
![2019-10-17_07 53 11](https://user-images.githubusercontent.com/56671397/66990160-def5a000-f0ef-11e9-9c57-0fce3524efc2.png)

I have architecture blocks darker than their parent blocks, but only with shaders. Without shaders everything's good. Does it depend of shaderpack? In the preview the blocks are normal with shaders.

![1528277868_architecturecraft-2](https://user-images.githubusercontent.com/56671397/66990187-eddc5280-f0ef-11e9-8bf9-d47c9d5ba58e.png)

The same problem appears without any mods except arhitecturecraft and any texture packs.

**Comment by miiichael** [comment]
More examples. The degree of difference varies with the shader chosen (I use chocapic here, though it's also noticable with wisdom shaders). It's definitely more noticeable with lighter coloured blocks; white wool becomes grey wool:

![2019-11-02_14 13 18](https://user-images.githubusercontent.com/4179353/68066977-51ff4780-fd7b-11e9-9f96-53504321de18.png)
![2019-11-02_14 14 33](https://user-images.githubusercontent.com/4179353/68066983-6fccac80-fd7b-11e9-829c-55fc69f78cfa.png)

Same version everything as OP, by coincidence.

**Comment by darkevilmac** [comment]
Architecturecraft does some weird stuff with rendering, honestly impressed it works at all with optifine let alone shaders.

Might end up working when I tear out all the rendering code and put some new stuff in. Not sure.

Anyway, optifine isn't supported. If you have rendering bugs with optifine and or shaders then I recommend you remove them.
