### ISSUE TITLE
dynmap/dynmapblockscan support

### ISSUE THREAD

**Issue by miiichael** [TridentMC/ArchitectureCraft#79]
Architecturecraft 1.12-3.98 on forge 1.12.2-14.23.5.2838.

Almost certainly well into wishlist/feature request category, but IWBNI [dynmapblockscan](https://github.com/webbukkit/DynmapBlockScan/issues/1) worked with architecturecraft. Dynmap-blockscan is an extension of [dynmap](https://www.curseforge.com/minecraft/mc-mods/dynmapforge) that attempts to adds support for blocks provided by mods.

At the moment it merely remarks in the log:

`[11:36:37] [Server thread/INFO] [DynmapBlockScan]: architecturecraft:assets/architecturecraft/blockstates/shape.json : Failed to open blockstate`

The unfortunate result is that Architecturecraft blocks are currently rendered invisibly by dynmap.

[This comment](https://github.com/webbukkit/DynmapBlockScan/issues/1#issuecomment-458725060) suggests that using the JSON-based model scheme is required to make this work. I hope this is not infeasible for you (but I'm not going to hold my breath :P). Info [here](https://old.reddit.com/r/feedthebeast/comments/bwa5q6/how_to_dynmap_mod_textures/) on the data that the blockscan generates may or may not be helpful too.

**Comment by CalmBit** [comment]
Yeah, this is a huge Wontfix. Absolutely not our bug and not a reasonable assumption of a mod to make. Sorry about that.
