### ISSUE TITLE
Crash when block placed in Tinkers Crafting Station

### ISSUE THREAD

**Issue by ghost** [TridentMC/ArchitectureCraft#8]
MC 1.12.1
Forge 2485
Tinkers 2.7.3.30
Architect 1.20

This is an 'old' bug which I had also reported in previous versions.
When placing an ArchitectureCraft block (e.g. wedge) in a Tinkers crafting station, the game crashes (in fact, java crashes). [Here is the log](https://paste.ee/p/Zw0U7).

**Comment by darkevilmac** [comment]
Probably missing a push and pop matrix and maybe a disable after enable...
