### ISSUE TITLE
Crash when interacting with a window frame

### ISSUE THREAD

**Issue by nexitem** [TridentMC/ArchitectureCraft#80]
https://gist.github.com/nexitem/4572f546ac8c9c1454b36cfff037d428

Not sure what else to tell you, many mods in this pack.

**Comment by kotoroshinoto** [comment]
I also experienced this. It accepted the glass pane fine, but when I attempted to remove it with the chisel it crashed.

**Comment by MrIngelborn** [comment]
Also experiencing this issue. Will see if I can do a pull reqest with a quickfix

**Comment by tyon2006** [comment]
Hey, I am getting this in 1.12-3.98 but i don't see a new version with the fix. Any suggestions?

**Comment by KorewaLidesu** [comment]
> Hey, I am getting this in 1.12-3.98 but i don't see a new version with the fix. Any suggestions?

check on CI
