### ISSUE TITLE
Strange Shadow Effects (Possibly Optifine)

### ISSUE THREAD

**Issue by MWG-Logan** [TridentMC/ArchitectureCraft#88]
When placing either the Sawbench or one of the custom blocks, it creates this strange jagged effect.
[Example](https://imgur.com/bwTzTDB)

- Version: 3.98
- MC Version: 1.12.2
- Forge Version: 14.23.5.2847
- Modpack: ATM3: Shedding Tiers, with some sprinkles
- [latest.log](https://github.com/TridentMC/ArchitectureCraft/files/3923755/latest.log)
-The issue seems to be occurring at around line 9600

**Comment by CalmBit** [comment]
Sorry, this is a bug with Optifine, not us.
