### ISSUE TITLE
IBlockColor and IItemColor not implemented

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TridentMC/ArchitectureCraft#9]
Thanks for reporting an issue to an Elytra project!

When reporting an issue to an Elytra project, please make sure to include:

- The version of the mod you are using (e.g. 2.0.0a4) architecturecraft-1.12-1.20.jar
- Your Minecraft version (e.g. 1.11.2) - 1.12.2
- Your Forge version (e.g. 13.20.0.2252) - 14.23.0.2489
- The crash report or log, uploaded to gist.github.com - N/A

Hey I just wanted to show you a video of how the mod interacts with Flat Colored Blocks Shades I will also be posting the interaction with the Flat Colored Blocks mod developer as well.

Video of Issues.
https://youtu.be/pAP9eMv-1LQ 

::NOTE:: Youtube messed up my video give me a second to fix
 Here I uploaded to streamable
https://streamable.com/p4z55

**Comment by darkevilmac** [comment]
![](https://i.imgur.com/nQdQqic.png)

Try this build, apparently the original dev didn't implement support for IBlockColor and IItemColor...
https://ci.elytradev.com/blue/organizations/jenkins/elytra%2FArchitectureCraft/detail/1.12/52/artifacts

**Comment by P3rf3ctXZer0** [comment]
I will test it for you :D

**Comment by P3rf3ctXZer0** [comment]
So yeah it crashes when something XD
https://gist.github.com/P3rf3ctXZer0/43cea897184ec4c98224b1095e0fc6c7

**Comment by darkevilmac** [comment]
That error log doesn't reference architecturecrafts codebase. It looks more like an issue with shaders.

**Comment by P3rf3ctXZer0** [comment]
It appeared after an update I will look into it later.

**Comment by P3rf3ctXZer0** [comment]
So for some reason archiecture craft has mess with all left click and right click block states ... I also noticed this when trying to do anything!

https://gist.github.com/P3rf3ctXZer0/b62801ecd46de571299cb6cfb83fd745

I could make a block have its color using workbench but the bench wouldn't give me the block.

These tests are done without - Optifine, betterfps and foamfix on either side.

**Comment by P3rf3ctXZer0** [comment]
Confirmed removing Architecture bench brings block interaction back to normal.

**Comment by darkevilmac** [comment]
Ah, it's an issue with my refactor, I haven't tested it on dedicated servers yet.

**Comment by darkevilmac** [comment]
@P3rf3ctXZer0 https://ci.elytradev.com/blue/organizations/jenkins/elytra%2FArchitectureCraft/detail/1.12/53/artifacts try this.

**Comment by P3rf3ctXZer0** [comment]
Testing now.

**Comment by P3rf3ctXZer0** [comment]
Alright works except it does not register glass flat blocks types. However thankfully it doesn't break the game anymore XD

**Comment by P3rf3ctXZer0** [comment]
I believe these issus are connected - https://github.com/elytra/ArchitectureCraft/issues/10

**Comment by darkevilmac** [comment]
> I believe these issus are connected - #10

They're not.

**Comment by lightlessfilms** [comment]
Sorry to reply on a closed bug report from ages ago.
But does anyone have the jar file of the url below? its archived, but that url does not show up.
https://ci.elytradev.com/blue/organizations/jenkins/elytra%2FArchitectureCraft/detail/1.12/53/artifacts
