### ISSUE TITLE
Inside curved corner

### ISSUE THREAD

**Issue by timmit99** [TridentMC/ArchitectureCraft#92]
Looking for poassible implementation of an Internal corner for the "Round Outer Corner". The block would look like this:
![](https://i.imgur.com/a99p6qo.png)

and would allow for the creation of things like this:
![2019-12-19_00 04 53](https://user-images.githubusercontent.com/8399317/71146451-4f559600-21f3-11ea-8598-241ac8413c67.png)
where the red block is in place of the desired block

Thanks

**Comment by CalmBit** [comment]
No new blocks are currently planned. Sorry.
