### ISSUE TITLE
Compatibility Issue with Some Shader

### ISSUE THREAD

**Issue by MakcSan** [TridentMC/ArchitectureCraft#96]
Mod version Alpha 1.12-3.98
MC 1.12.2
Forge Version 1.12.2-14.23.5.2847
i have SEUS PTGI and PBR Textures (but it can be almost any shaders and any pbr textures)
Edited due to wacky infomation scroll down

**Comment by MakcSan** [comment]
Due to wacky infomation i will may open this later

**Comment by MakcSan** [comment]
![2020-04-26_12 22 23](https://user-images.githubusercontent.com/60064880/80296759-9adb0a80-87b8-11ea-970b-75e6c579f751.png)
Its lot better than before, i was just using diffrent blocks 
But still feel weird

**Comment by MakcSan** [comment]
![2020-04-26_12 34 52](https://user-images.githubusercontent.com/60064880/80297013-5f414000-87ba-11ea-8b8f-2cb83b1ddcff.png)
This Invisible Block im looking to is Sawbenched Glass that has some PBR textures
Its waving like water

**Comment by CalmBit** [comment]
Shader support is not assured, as the bugs are typically not on our end. Shader code makes particular assumptions about Minecraft blocks that we don't necessarily honour. Sorry.
